/*
    Copyright 2026, Strategic Gains, Inc.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/
package com.strategicgains.repoexpress.jdbc.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks an entity field as part of the primary identifier.
 * Composite identifiers are supported by setting a unique order per field.
 * <p/>
 * At least one {@code @Id} is required for entities generated by
 * {@code JdbcEntityDefinitionFactory}.
 *
 * @author toddf
 * @since Feb 26, 2026
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Id
{
	/**
	 * Identifier component order for composite keys.
	 * For single-column keys, default {@code 0} is sufficient.
	 *
	 * @return component order used when building id field metadata.
	 */
	public int order() default 0;
}
