/*
    Copyright 2026, Strategic Gains, Inc.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/
package com.strategicgains.repoexpress.jdbc.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Maps a POJO field to a JDBC column and controls query/update participation.
 * <p/>
 * If a field has {@code @Id} and no {@code @Property}, defaults are derived from
 * the Java field name and all flags default to {@code true}, except update handling
 * where id fields are excluded from updates by the factory.
 *
 * @author toddf
 * @since Feb 26, 2026
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Property
{
	/**
	 * Physical column name.
	 * If empty, the Java field name is used.
	 *
	 * @return mapped column name.
	 */
	public String value() default "";

	/**
	 * Logical query field name used with repository helpers and QueryFilter/QueryOrder.
	 * Supports dotted logical names such as {@code account.id}.
	 * If empty, the Java field name is used.
	 *
	 * @return logical query field name.
	 */
	public String queryName() default "";

	/**
	 * Whether the property is exposed for filter lookup through definition.field(...).
	 *
	 * @return true if queryable.
	 */
	public boolean queryable() default true;

	/**
	 * Whether the property is exposed for sort lookup through definition.field(...).
	 *
	 * @return true if sortable.
	 */
	public boolean sortable() default true;

	/**
	 * Whether the property is included in insert values generated by the factory.
	 * Set false for server-generated columns (for example, trigger-populated values).
	 *
	 * @return true if insertable.
	 */
	public boolean insertable() default true;

	/**
	 * Whether the property is included in update values generated by the factory.
	 * {@code @Id} fields are never updated, regardless of this flag.
	 *
	 * @return true if updatable.
	 */
	public boolean updatable() default true;
}
